---
- name: "update cache"
  become: yes
  apt:
    update_cache: yes

- name: "apache install"
  become: yes
  apt:
    name: apache2
    state: latest

- name: "start apache2 service"
  become: yes
  service:
    name: apache2
    state: started