---

- name: "create group"
  become: yes
  group:
    name: "{{ group_name }}"
    state: present

- name: "create user"
  become: yes
  user:
    name: "{{ user_name }}"
    state: present
    group: "{{ group_name }}"
    shell: /bin/bash
    password: user_password
    home: "/home/test-user-1"

- name: "create directory"
  file:
    path: /home/ubuntu/static-files
    state: directory
    mode: '0755'

- name: "upload project to directory"
  become: yes
  copy:
    src: /home/uday/week-1-code/eSparkHTML/
    dest: /home/ubuntu/static-files/

- name: "update cache"
  become: yes
  apt:
    update_cache: yes

- name: "install nginx"
  become: yes
  apt:
    name: nginx
    state: latest

- name: "start nginx"
  become: yes
  service:
    name: nginx
    state: started
    enabled: true

- name: "add static project to nginx"
  become: yes
  copy:
    src: /home/ubuntu/static-files/
    dest: /var/www/html/
    remote_src: yes